### ISSUE TITLE
Consolidate websites

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/website-old#129]
# Description

We current have the specs website distinct from the main website at frictionlessdata.io. There are historical reasons for this. The impact of this now is that things get out of sync, and there is no tight relationship between important elements, such as the specs themselves, and the guides that provide explanatory detail and usage of tools that implement the specs.

Further, there is quite a large amount of duplication across the sites.

We want to merge the specs and the main website into one in order to address these issues. @danfowler and I have agreed on what is needed here. The proposed solution is to:

- Convert frictionlessdata.io to a Lektor site
- Remove a range of sections from this site
- Copy over the specs, into the existing fd.io templates, and serve the specs from `fd.io/specs/`
- Merge several sections from the specs site into fd.io (remove duplication)
- Copy over the tooling for generating spec schemas and so forth
- Do a redesign of fd.io once the content has been refactored via the above steps

# Goal

A single web property for Frictionless Data with specs, guides, and tooling.

# Tasks

- [x] Plan design work for fd.io as part of of final work design push for current stage of work
- [x] PR to make fd.io a Lektor site
- [x] Remove content / refactor content architecture on frictionlessdata.io based on work @smth has already done, and the "Content architecture" section below, prepared by @pwalsh and @danfowler 
- [x] Change "specifications and tools" to "specifications and software" in the header
  - [x] In general, let's move away from "tools" and use "software"
- [x] Tools tagging and filtering
  - [x] Use the following tags. Use the description sentence at the top when the filter is selected
    - [x] All: Publicly-available software that leverages Frictionless Data specifications and software
    - [ ] Platforms: Web-based platforms by Open Knowledge International and partner maintainers that leverage the Frictionless Data ecosystem
      - datahub.io, goodtables.io, Open Spending
        - These should feature at the top of the page
    - [x] Apps: Apps by Open Knowledge International and partner maintainers that leverage the Frictionless Data ecosystem
      - Data Package Pipelines
      - Data Curator
      - Stenci.la (coming soon)
    - [x] Libraries: Core libraries by Open Knowledge International and partner maintainers that leverage the Frictionless Data ecosystem
      - All the core libraries we and the maintainers we support do
    - [x] Universe: Platforms, apps and libraries by the wider community that leverage the Frictionless Data ecosystem
      - Everything else we know about, from data.world, to tesera, to datapackage-m

## Content architecture

- `/get-involved/` can be removed, and the content integrated into home page or the footer, and specs home page will merge into the home page
- `/faq/` FAQ can merge with specs FAQ
- `/about/` can be removed, and also any relevant content go to the home page
- `/user-stories/` just needs to be linked to from a good place(s), and doesnt need a page
- `/data-packages/` and sub packages - completely merge with spec pages
- `/tools/` Tools is great and we can probably invest some time to making better, and especially highlighting datahub.io and goodtables.io as primary, high-level tools
- `/roadmap/` Can be removed
- `/guides/` can be updated specifically based on @danfowler 's proposal
- `/partners/` remove this page, and instead have very high-level partners (funders) in footer, and other partners in context on the `/studies/` page and `/tools/`
- “Find data packages” remove from navigation
- `/case-studies/` Based on existing pattern, this should be widened conceptually as the gateway to any write-ups on case studies and pilots

**Comment by pwalsh** [comment]
Integrate #105

**Comment by pwalsh** [comment]
Integrate #103

**Comment by pwalsh** [comment]
Integrate #9

**Comment by rufuspollock** [comment]
@pwalsh my big concern is the sync between the specs issue tracker and the specs - in this model we will lose this. We will have the specs issue tracker still (i assume) but the actual specs will now live on fd.io content site. How will that get handled ...

Note: in terms of user stories:

> The impact of this now is that things get out of sync, and there is no tight relationship between important elements, such as the specs themselves, and the guides that provide explanatory detail and usage of tools that implement the specs.

I don't think this has much to do with the technical separation between the sites. It could happen even if the same site - the source of this is other issues. I'd be cautious in imagining that simply merging the two sites will help this.

> Further, there is quite a large amount of duplication across the sites.

What duplication do we have that we could eliminate easily?

My general 2c: a simple update of the fd.io theme is a few hours work at most whilst this project is quite substantial and requires, redirects, new workflows for spec work etc. Right now I'd really go for the MVP and just update the specs website theme which is super easy. Once we have done that we have breathing space to really think about the merge and do it right (and without the risk that merging the sites impacts on v1 specs release).

**Comment by roll** [comment]
Could `specs` repo end-up as a 100% technical repository (only spec texts and jsonschemas)? And fd.io will have it as a submodule or something?

Even current situation with `specs` repo is not I deal in my mind because at the same issue tracker we handle both actual specs issues and thing like fixing design etc. Also I suppose the best situation when your tech specifications exists on top of repo, not inside folders for site building

**Comment by danfowler** [comment]
> @roll: Also I suppose the best situation when your tech specifications exists on top of repo, not inside folders for site building

@roll @pwalsh It might make sense just to commit the [compiled schemas](https://github.com/frictionlessdata/specs/tree/master/assets/schemas) to the repo along with a note saying that PRs will not be accepted on the compiled schemas and to look for the [YAML source dictionaries](https://github.com/frictionlessdata/specs/tree/master/sources/dictionary) for any changes.  (We might even just plop a `README.md` file in that directory to make clear to new users what is happening here.)

---

> @roll: Even current situation with specs repo is not I deal in my mind because at the same issue tracker we handle both actual specs issues and thing like fixing design etc. 

> @rufuspollock: We will have the specs issue tracker still (i assume) but the actual specs will now live on fd.io content site. How will that get handled ...

I suppose this will enforce the idea that the only changelog worth following is the public changelog at the top of each specification.  If we still want the workflow of closing issues on specs repo via commits on the frictionlessdata.io repo, we can [still do that](https://help.github.com/articles/closing-issues-via-commit-messages/).

> @rufuspollock: I don't think this has much to do with the technical separation between the sites. It could happen even if the same site - the source of this is other issues. I'd be cautious in imagining that simply merging the two sites will help this.

In removing the duplication between the two sites as well as any low value content on the frictionlessdata.io site, we are left with only three valuable types of content on the main site: `/tools/`, `/case-studies/`, and `/guides/`.  At that point, why not have a one-stop shop?

---

> @rufuspollock: What duplication do we have that we could eliminate easily?

e.g. http://frictionlessdata.io/guides/data-package/

To the extent that there is information in http://frictionlessdata.io/guides/data-package/ that doesn't exist in actual spec page, it clearly belongs on a much more specific guide.

---

> @roll Could specs repo end-up as a 100% technical repository (only spec texts and jsonschemas)? And fd.io will have it as a submodule or something?

That could work, but would want something other than a submodule connecting the two.  And could still lead to a situation where the specs repo continues on and the frictionlessdata.io doesn't represent the latest changes.

**Comment by roll** [comment]
@danfowler 
If there will be a decision to do like I said we're pretty capable to easily solve any problems e.g. triggering fd.io rebuild on any push to specs (I've tested it for testsuite) and using just simple wget instead of submodule etc.

**Comment by rufuspollock** [comment]
Let me reiterate: I get the idea of merging sites. I'm just saying:

A. Can we do the simplest thing first of updating specs css (which takes a couple of hours)

B. We almost certainly underestimate the effort of merging the sites and the benefits in terms of maintainability seem relatively low atm (the big issue is updating content - which does not depend on the separation or not of the sites).

**A** is the really important point - forget B if you like!

**Comment by serahkiburu** [comment]
@danfowler @pwalsh, just flagging that, I added /grantee-profiles/ last Friday as well, not sure if this will still be a stand-alone page in the new site cc @jobarratt

**Comment by danfowler** [comment]
@pwalsh @jobarratt @callmealien great, I think this could possibly fit into the conceptually widened "case studies" page whatever it ends up being called.

> - `/case-studies/` Based on existing pattern, this should be widened conceptually as the gateway to any write-ups on case studies and pilots

@rufuspollock 

> A. Can we do the simplest thing first of updating specs css (which takes a couple of hours)

The work of moving the current fd.io site to Lektor is similarly simple, and is a concrete first step that can be done independently of actually merging the specs.  It will make merging the specs actually possible.

**Comment by rufuspollock** [comment]
@danfowler but updating the fd.io site to lektor is completely distinct task (that is probably a non-trivial amount of work) and does **not** fix the actual issue which is that the specs.fd.io site does not look consistent and has poor readability / elegance.

Can we *please* fix the actual main issue right now which is specs.fd.io css and then come back to any discussion re merging sites (which IMO is a side issue from the main tasks at hand!)

**Comment by Stephen-Gates** [comment]
Would love to have a way to easily get back to fd.io from specs.fd.io. I have tabs for both open in my browser due to the lack of navigation.

**Comment by smth** [comment]
To update on the work I'm doing towards this issue. I have started building a new, Lektor based site [here](http://p.smth.uk/frictionlessdata/), based on my below designs.

![frictionlessdata_02_home_01](https://user-images.githubusercontent.com/1375708/30633443-8f364382-9de3-11e7-935e-760d0440cae0.jpg)

![frictionlessdata_02_casestudies_01](https://user-images.githubusercontent.com/1375708/30633450-967c3548-9de3-11e7-887e-dcb8478889b6.jpg)

![frictionlessdata_02_specs_01](https://user-images.githubusercontent.com/1375708/30633459-9c1674a0-9de3-11e7-85b8-b2a1cd904031.jpg)

**Comment by smth** [comment]
[Grantee profiles](http://frictionlessdata.io/grantee-profiles/) is missing from the above structure, and needs somewhere to live. Perhaps we reintroduce an "About" section to house these sorts of things.

**Comment by jobarratt** [comment]
@smth my view is that it's going to be more effective as another category in "articles" than creating an "About" section.

**Comment by rufuspollock** [comment]
Is there any structure for feedback/input and any list of user stories for this rework that one can contribute to or review? (Happy to leave this to you @jobarratt  if that works  best!)

**Comment by jobarratt** [comment]
@rufuspollock Sam is continuing to work on this over the week and we're going to open this up to comments and feedback at the beginning of next week. I will share then and it would be great to get you input.

**Comment by rufuspollock** [comment]
@jobarratt great - will that be at the user story stage for input or  "here's the finished website" point? (the latter is generally a bit late for useful input ...)

**Comment by jobarratt** [comment]
@rufuspollock will be the latter stage. A design based on the content architecture above.

**Comment by jobarratt** [comment]
@rufuspollock we are not quite there yet with the site. But you are welcome to review Sam's work in progress http://p.smth.uk/frictionlessdata/ and we are collating general comments here: https://docs.google.com/document/d/1bDMIGIW2b-WHFDu8zOXSPFFpcaPDz_rA1_we2YbRdS0/edit#

**Comment by pwalsh** [comment]
@callmealien @jobarratt 

The branch with new design and Lektor implementation from @smth is linked from the above pull request link.

The bucket for serving this site from AWS S3 is now `frictionlessdata.io`. Until we switch over the main site is accessible at [http://frictionlessdata.io.s3-website-eu-west-1.amazonaws.com/](http://frictionlessdata.io.s3-website-eu-west-1.amazonaws.com).

This issue now remains open for the content architecture tasks. The task list in the [first post](https://github.com/frictionlessdata/website/issues/129#issue-236099845) on the thread has ben updated to reflect this.

A [separate issue has been opened for integrating the specs into this repo](https://github.com/frictionlessdata/website/issues/142), and I suggest that @roll does this before moving forward to next tasks.
