### ISSUE TITLE
Website update: Pull in specs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/website-old#142]
# Description

In #129 we noted we will consolidate the specs and the "promotional" website for Frictionless Data, based on research and decisions that Dan and I took. Much of the work has been done by @smth , and some remaining content consolidation is being done before we close #129 by @callmealien . 

What's left? bringing over the content from https://github.com/frictionlessdata/specs when we build the website. I've done a thorough review and I note below the steps I think we need to take to do this. @roll adjust as you see fit.

# Tasks

- [x] Create a new branch on frictionlessdata/specs and remove all the Lektor stuff, and just keep the spec texts, and all the schemas and specs generation code.
  - [x] In each spec text, get rid of the `_model` key
  - [x] put the specs texts into `specs` at the root, and the schemas into `schemas` at the root
- [x] In the website repo, have a file or something else to declare a git commit or a git tag - this will be the commit or tag for the specs version to be built with the website
- [x] write a script to pull in `specs` and `schemas` from the specs website (using the new branch you are working on). specs will have to go into `content` on the website codebase, and `schemas` will have to go into `assets`. Note that this is similar to current structure of the specs website
- [x] Do a PR on specs, for the new branch onto master. Then @pwalsh can review and see what to do with the other things - old templates etc.
- [x] Do a 301 redirect for all routes on specs.frictionlessdata.io to frictionlessdata.io (**only when we go live with the new design**)

# Outcome

The specs repo will only have:

1. Specification texts
2. Issue tracker
3. Schemas, and code to generate and manipulate them

The website repo will have:

1. A build process that pulls in the latest specs and schemas (according to tag or git commit)
2. Specs served under `/specs/`
3.. Schemas served under `/schemas/`

All old specs URLs will redirect to the same content on the main frictionlessdata.io website.

**Comment by smth** [comment]
Perhaps we should also fix the headings hierarchy. Currently the pages have two `h1`s. All headings probably need shifting down by one.

**Comment by smth** [comment]
Also there's some: `<div class="alert alert-warning security"></div>` that need to be replaced with Markdown, as I noted [here](https://github.com/smth/frictionlessdata#notes--warnings).
