### ISSUE TITLE
Sprint 25 April - 2nd May 2016

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#3]
Read Information Architect overview first: #2
# Bigger Stuff

In approximate priority order:
- [x] `/doc/`\- #4 
  - [x] First tutorial - on Python (Dan) - https://github.com/frictionlessdata/ideas/issues/221
- [x] `/tools/` #5 Tools page: revert to the old approach
- [ ] `/user-stories/` #7 
- [x] `/data-packages/`(currently `/standards/`) #9

Probably not this iteration:
- `/` - improvements to front page
# Misc
- [ ] <del>Hide "donate", "share" buttons on all pages (not really needed for this type of site)</del> (may as well leave these ...)
- [x] Show "edit this page" button by default (in _config.yml) and then turn off where needed
- [x] Update the README to something sensible
- [ ] Handbook theme should link to IP policy as well as terms of use ... (and that should then be pulled through to here)
- [ ] <del>Create sections to break up sidebar ToC a bit (??) - not a priority as will probably reflect overall architectute</del>

**Comment by rufuspollock** [comment]
CLOSING as sprint over. Note IP Policy etc is #23 and user stories work is ongoing in https://github.com/frictionlessdata/ideas/issues/245
